In [48]:
from numpy.random import seed
seed(1)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from analysis import *
from collections import namedtuple
import Metrics
from PatientSet import PatientSet
from Constants import Constants
from dependencies.Boruta import BorutaPy

#for getting the fisher exact test
import rpy2.robjects.numpy2ri
from rpy2.robjects.packages import importr
rpy2.robjects.numpy2ri.activate()

#sklearn dependencies
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import recall_score, roc_auc_score, f1_score
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.utils import resample
from scipy.cluster.hierarchy import fcluster, linkage

#we get like a million deprication errors for some reason with the external libraries
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [64]:
#class wrapper with for heirarchical clustering with more linkages than sklearn
class FClusterer():
    
    def __init__(self, n_clusters, dist_func = l1, link = 'weighted', criterion = 'maxclust'):
        self.link = link
        self.dist_func = dist_func if link not in ['median', 'ward', 'centroid'] else 'euclidean'
        self.t = n_clusters
        self.criterion = criterion

    def fit_predict(self, x, y = None):
        clusters = linkage(x, method = self.link, metric = self.dist_func)
        return fcluster(clusters, self.t, criterion = self.criterion)

def l1(x1, x2):
    return np.sum(np.abs(x1-x2))

def tanimoto_dist(x1, x2):
    if l1(x1 - x2) == 0:
        return 0
    tanimoto = x1.dot(x2)/(x1.dot(x1) + x2.dot(x2) - x1.dot(x2))
    return 1/(1+tanimoto)

def l2(x1, x2):
    return np.sqrt(np.sum((x1-x2)**2))

def pdist(x, dist_func):
    distance = []
    for i in range(x.shape[0]):
        for j in range(x.shape[0]):
            distance.append(dist_func(x[i], x[j]))
    return np.array(distance)
    

In [65]:
cluster_result = namedtuple('cluster_result', ['method', 'cluster', 'correlation', 'model'])

def get_clusterers(ks = [2,5]):
    c_range = range(ks[0], ks[1])
    clusterers = {}
    clusterers['l1_weighted'] = [FClusterer(c) for c in c_range]
    clusterers['l2_weighted'] = [FClusterer(c, dist_func = l2) for c in c_range]
    clusterers['l1_complete'] = [FClusterer(c, link = 'complete') for c in c_range]
    clusterers['l2_complete'] = [FClusterer(c, dist_func = l2, link = 'complete') for c in c_range]
    clusterers['centroid'] = [FClusterer(c, link='centroid') for c in c_range]
    clusterers['median'] = [FClusterer(c, link = 'median') for c in c_range]
    clusterers['ward'] = [FClusterer(c, link='ward') for c in c_range]
    return clusterers

def fisher_exact_test(c_labels, y):
    if len(set(y)) == 1:
        print('fisher test run with no positive class')
        return 0
#        assert(len(set(y)) == 2)
    #call fishers test from r
    contingency = get_contingency_table(c_labels, y)
    stats = importr('stats')
    pval = stats.fisher_test(contingency)[0][0]
    return pval

def get_contingency_table(x, y):
    #assumes x and y are two equal length vectors, creates a mxn contigency table from them
    cols = sorted(list(np.unique(y)))
    rows = sorted(list(np.unique(x)))
    tabel = np.zeros((len(rows), len(cols)))
    for row_index in range(len(rows)):
        row_var = rows[row_index]
        for col_index in range(len(cols)):
            rowset = set(np.argwhere(x == row_var).ravel())
            colset = set(np.argwhere(y == cols[col_index]).ravel())
            tabel[row_index, col_index] = len(rowset & colset)
    return tabel

def analyze_clusters(target_var, name, clusterer, features):
    result = []
    clusters = clusterer.fit_predict(features).ravel()
    n_clusters = len(set(clusters))
    if n_clusters < 2:
        return None
    method = name + str(n_clusters)

    overall_correlation = fisher_exact_test(clusters, target_var)
    result.append( cluster_result(method, 'all',
                                  overall_correlation,
                                  clusterer))

    for c in np.unique(clusters):
        correlation = fisher_exact_test(clusters == c, target_var)
        result.append( cluster_result(method, str(c+1),
                                      correlation, clusterer))
    return result

def cluster(target_var, features, args = None):
    if args is not None:
        assert( isinstance(args, list) )
        features = features[:, args]
    results = []
    clusterers = get_clusterers()
    for cname, clusterers in clusterers.items():
        for clusterer in clusterers:
            analysis = analyze_clusters(target_var, cname, clusterer, features)
            if analysis is not None:
                results.extend(analysis)
    results = sorted(results, key = lambda x: x.correlation)
    return results

def get_optimal_clustering(features, target_var, args = None, patient_subset = None):
    clusters = np.zeros(target_var.shape)
    if patient_subset is not None:
        target = target_var[patient_subset]
        features = features[patient_subset,:]
    else:
        target = target_var
    result = cluster(target, features, args)
    result = [r for r in result if r.cluster is 'all']
    if args is not None:
        features = features[:, args]
    clusters[patient_subset] = result[0].model.fit_predict(features).ravel() + 1
    pval = fisher_exact_test(clusters, target_var)
    clusterer_data = cluster_result(method = result[0].method,
                                    cluster = result[0].cluster,
                                    correlation = pval,
                                    model = result[0].model)
    optimal = (clusters, clusterer_data)
    return optimal


In [66]:
#load in the patientset object that has all the patient info
db = PatientSet()

#add a bunch of features to the object that we'll want to try
#so we can use the db.to_dataframe function to get them all in a nice dataframe with one-hot encoding and labels automatically
db.discrete_dists = Metrics.discretize(-db.tumor_distances, n_bins = 15, strategy='uniform')
db.t_volumes = np.array([np.sum([g.volume for g in gtvs]) for gtvs in db.gtvs]).reshape(-1,1)
db.tsimdoses = tsim_prediction(db)
db.toxicity = db.feeding_tubes + db.aspiration > 0
db.xerostima = db.feeding_tubes + db.aspiration > 1

Index(['ROI', 'Age at Diagnosis (Calculated)', 'Pathological Grade', 'Gender',
       'Race', 'Therapeutic combination', 'Tm Laterality (R/L)',
       'Tumor subsite (BOT/Tonsil/Soft Palate/Pharyngeal wall/GPS/NOS)',
       'Affected Lymph node', 'Affected Lymph node cleaned', 'N-category',
       'HPV/P16 status', 'T-category', 'AJCC 7th edition', 'AJCC 8th edition',
       'Smoking status at Diagnosis (Never/Former/Current)',
       'Smoking status (Packs/Year)', 'Neck boost (Y/N)', 'Total dose',
       'Total fractions', 'Feeding tube 6m', 'Aspiration rate Pre-therapy',
       'Aspiration rate Post-therapy', 'Aspiration rate(Y/N)'],
      dtype='object')


D:\git_repos\CAMP-RT\PYTHON\Patient.py:359: RuntimeWarning: invalid value encountered in true_divide
  mean_tumor_distances /= tumor_volume
D:\git_repos\CAMP-RT\PYTHON\Patient.py:360: RuntimeWarning: invalid value encountered in true_divide
  tumor_position /= tumor_volume


100 [{0, 1}, {2}]
128 [{0}, {1, 2, 3, 4}]
notation not accounted for in lymph nodes: R3/R4
notation not accounted for in lymph nodes: L2/3
notation not accounted for in lymph nodes: R3/4
notation not accounted for in lymph nodes: R2/3
notation not accounted for in lymph nodes: R2-R4
notation not accounted for in lymph nodes: L2/3
notation not accounted for in lymph nodes: L2/3
notation not accounted for in lymph nodes: L2/3
notation not accounted for in lymph nodes: R2/3
notation not accounted for in lymph nodes: R2/3/4
notation not accounted for in lymph nodes: L2/3
notation not accounted for in lymph nodes: L2/3
notation not accounted for in lymph nodes: R2/3
notation not accounted for in lymph nodes: R2/3
notation not accounted for in lymph nodes: R2/3
10021 [{0, 1}, {2}]
10074 [{0, 1}, {2}]
error reading tumor volume for  10091
error reading tumor volume for  10148
10191 [{0, 1}, {2}]

patient data loaded...



In [67]:
#parameters for the experiments
toxicities_to_test = ['feeding_tubes', 'aspiration', 'toxicity', 'xerostima']

#features to test the feature selection on.  should be fields in the patientset we have
candidate_features = ['discrete_dists', 'volumes', 't_volumes', 'lateralities']

#number of times to resample and doing feature selection
n_samples = 10

#type of scaling to use
scaler = MinMaxScaler()

#put some bounds on the features to subset
min_features = 2

#class used to subset the data, default is what the original paper suggests, roughly
boruta = BorutaPy(RandomForestClassifier(n_estimators = 300, max_depth = 10), n_estimators = 400)

#where to save results, put None if you don't want to save
save_root = 'data/clustering_results/'

In [68]:
#our actual experiment, try to find correlations using the boruta method and such
for tox_name in toxicities_to_test:
    print(tox_name)
    toxicity = getattr(db, tox_name) > 0
    
    #use actual doses to train, and predicted for the clustering 
    train = db.to_dataframe(candidate_features + ['doses'])
    test = db.to_dataframe(candidate_features + ['tsimdoses'])
    
    #we're going to resample the data, scale it, and apply the boruta method n_sample times
    def get_resampled_support(x, y):
        x, y = resample(x.values, y)
        x = scaler.fit_transform(x)
        boruta.fit(x, y)
        return boruta.support_, boruta.support_weak_
    
    #save the boruta support for each trial in a dataframe, scores are % of time the variable has support or weak support
    supports = pd.DataFrame(data = np.zeros((2,train.shape[1])), columns = test.columns, index =['support', 'weak_support'])
    for n in range(n_samples):
        sup, weak_sup = get_resampled_support(train, toxicity)
        supports.loc['support'] += sup/n_samples
        supports.loc['weak_support'] += weak_sup/n_samples
        
    #try out a bunch of thresholds on how good the variable is supported vs cluster results
    best_correlation = 1
    prev_argcount = test.shape[1]
    for support_thresh in [.2,.3,.4,.5,.6,.7,.8,.9]:
        top_args = np.argwhere(supports.loc['support'] >= support_thresh).ravel()
        if len(top_args) < min_features:
            break
        #check to see that we actually added more features
        if len(top_args) == prev_argcount:
            continue
        prev_argcount = len(top_args)
        to_use = test.iloc[:, top_args]
        print('number of features: ', len(train.columns[top_args]))
        
        #we're going to try a bunch of different clusterings and look at the best result
        clustering = get_optimal_clustering(scaler.fit_transform(to_use.values), toxicity)
        print(clustering[1].method)
        print(get_contingency_table(clustering[0], toxicity))
        print('correlation: ', clustering[1].correlation,'\n')
        #save the feature set with the best (lowest) correlation
        if clustering[1].correlation < best_correlation:
            best_correlation = clustering[1].correlation
            best_clusters = clustering[0]
            best_features = copy(to_use)
            n_best_clusters = len(set(clustering[0]))
            
    #check that we actually got a result
    if best_correlation == 1:
        print('no good values')
        break
    best_features['cluster_labels'] = best_clusters
    print(best_features.columns)
    
    if save_root is not None:
        best_features.to_csv(save_root
                     + 'boruta_features_k='
                     + str(n_best_clusters)
                     + '_p=' + '{:.3e}'.format(best_correlation)
                     + '_toxicity=' + tox_name + '.csv')

feeding_tubes


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


number of features:  43
l1_weighted3
[[140.   9.]
 [  1.   1.]
 [ 37.  12.]]
correlation:  0.0003217945067118481 

number of features:  26


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


l1_complete2
[[ 32.  12.]
 [146.  10.]]
correlation:  0.0003916572707262409 

number of features:  18


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


l2_complete2
[[ 30.  11.]
 [148.  11.]]
correlation:  0.0009855956226715876 

number of features:  10


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


l1_weighted4
[[ 28.   9.]
 [  0.   3.]
 [ 38.   0.]
 [112.  10.]]
correlation:  5.626061449086981e-06 

number of features:  6


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


l1_complete4
[[ 35.   2.]
 [114.   7.]
 [  0.   2.]
 [ 29.  11.]]
correlation:  2.015018807384979e-05 

number of features:  4


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


l2_complete3
[[133.   9.]
 [ 45.  12.]
 [  0.   1.]]
correlation:  0.0007348280618609464 

Index(['Lt_Submandibular_Gland_discrete_dists', 'Brainstem_volumes',
       'Larynx_volumes', 'Rt_Masseter_M_volumes', 'Lt_Masseter_M_volumes',
       't_volumes_0', 'SPC_tsimdoses', 'Rt_Submandibular_Gland_tsimdoses',
       'Genioglossus_M_tsimdoses', 'Extended_Oral_Cavity_tsimdoses',
       'cluster_labels'],
      dtype='object')
aspiration


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


number of features:  37
l2_complete2
[[ 40.  15.]
 [141.   4.]]
correlation:  1.2662065975780229e-06 

number of features:  23


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


ward4
[[28. 11.]
 [65.  2.]
 [38.  6.]
 [50.  0.]]
correlation:  7.125915470939396e-06 

number of features:  18


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


l1_complete3
[[ 23.  11.]
 [ 43.   0.]
 [115.   8.]]
correlation:  1.2961055591089437e-05 

number of features:  12


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


l1_weighted4
[[153.   9.]
 [ 11.   9.]
 [ 16.   1.]
 [  1.   0.]]
correlation:  2.5363129934610547e-05 

number of features:  11


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


l2_weighted3
[[99.  2.]
 [70.  8.]
 [12.  9.]]
correlation:  1.9656462494616247e-06 

number of features:  10


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


l2_complete4
[[18.  9.]
 [38.  7.]
 [43.  3.]
 [82.  0.]]
correlation:  8.09442282937395e-07 

Index(['SPC_discrete_dists', 'Cricoid_cartilage_volumes', 'Brainstem_volumes',
       'Cricopharyngeal_Muscle_tsimdoses', 'Rt_thyroid_lobe_tsimdoses',
       'Cricoid_cartilage_tsimdoses', 'Brainstem_tsimdoses',
       'Larynx_tsimdoses', 'Thyroid_cartilage_tsimdoses',
       'Soft_Palate_tsimdoses', 'cluster_labels'],
      dtype='object')
toxicity


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


number of features:  55
l2_weighted3
[[132.  11.]
 [ 34.  22.]
 [  0.   1.]]
correlation:  8.240579421581145e-08 

number of features:  37


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


l2_complete2
[[ 36.  25.]
 [130.   9.]]
correlation:  1.3401768922443206e-08 

number of features:  28


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


ward2
[[ 25.  23.]
 [141.  11.]]
correlation:  1.961974542280713e-09 

number of features:  19


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


l1_weighted2
[[ 24.  21.]
 [142.  13.]]
correlation:  4.021399663976596e-08 

number of features:  15


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


ward2
[[ 29.  25.]
 [137.   9.]]
correlation:  3.947782206362179e-10 

number of features:  10


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


l2_weighted2
[[ 29.  23.]
 [137.  11.]]
correlation:  1.6784122362814088e-08 

number of features:  3


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


l2_complete2
[[ 26.  22.]
 [140.  12.]]
correlation:  2.073294569077749e-08 

Index(['Lt_Brachial_Plexus_volumes', 'Brainstem_volumes',
       'Rt_Sternocleidomastoid_M_volumes', 'Lt_Masseter_M_volumes',
       't_volumes_0', 'MPC_tsimdoses', 'Lt_Submandibular_Gland_tsimdoses',
       'SPC_tsimdoses', 'Rt_Submandibular_Gland_tsimdoses',
       'Hyoid_bone_tsimdoses', 'Soft_Palate_tsimdoses',
       'Genioglossus_M_tsimdoses', 'Tongue_tsimdoses',
       'Extended_Oral_Cavity_tsimdoses', 'Mandible_tsimdoses',
       'cluster_labels'],
      dtype='object')
xerostima


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


number of features:  15
ward4
[[36.  4.]
 [43.  0.]
 [42.  3.]
 [72.  0.]]
correlation:  0.005627597244060792 

number of features:  9


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


median4
[[158.   3.]
 [ 35.   2.]
 [  0.   1.]
 [  0.   1.]]
correlation:  0.00047960983209218615 

number of features:  3


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


centroid3
[[  0.   2.]
 [193.   4.]
 [  0.   1.]]
correlation:  2.6648393482563565e-05 

Index(['Cricoid_cartilage_volumes', 'Brainstem_volumes', 'Brainstem_tsimdoses',
       'cluster_labels'],
      dtype='object')


C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)
